//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemoApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        internal static string AlphaTab_Title {
            get {
                return ResourceManager.GetString("AlphaTab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        internal static string BetaTab_Title {
            get {
                return ResourceManager.GetString("BetaTab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Button_Finish {
            get {
                return ResourceManager.GetString("Button_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        internal static string Button_GoBack {
            get {
                return ResourceManager.GetString("Button_GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Button_Login {
            get {
                return ResourceManager.GetString("Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Alpha.
        /// </summary>
        internal static string Button_SwitchToAlpha {
            get {
                return ResourceManager.GetString("Button_SwitchToAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Beta.
        /// </summary>
        internal static string Button_SwitchToBeta {
            get {
                return ResourceManager.GetString("Button_SwitchToBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Charlie.
        /// </summary>
        internal static string Button_SwitchToCharlie {
            get {
                return ResourceManager.GetString("Button_SwitchToCharlie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your username.
        /// </summary>
        internal static string ChangeUsername_Heading {
            get {
                return ResourceManager.GetString("ChangeUsername_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This modal will return data to the previous page even if you don&apos;t use the &apos;Finish&apos; button..
        /// </summary>
        internal static string ChangeUsername_Instructions {
            get {
                return ResourceManager.GetString("ChangeUsername_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change username.
        /// </summary>
        internal static string ChangeUsername_Title {
            get {
                return ResourceManager.GetString("ChangeUsername_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        internal static string ChangeUsername_UsernamePlaceholder {
            get {
                return ResourceManager.GetString("ChangeUsername_UsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charlie.
        /// </summary>
        internal static string CharlieTab_Title {
            get {
                return ResourceManager.GetString("CharlieTab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contacts_Title {
            get {
                return ResourceManager.GetString("Contacts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout.
        /// </summary>
        internal static string DemoFlyout_Title {
            get {
                return ResourceManager.GetString("DemoFlyout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabbed Page.
        /// </summary>
        internal static string DemoTabs_Title {
            get {
                return ResourceManager.GetString("DemoTabs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add multiple pages.
        /// </summary>
        internal static string Home_Button_AddMultiplePages {
            get {
                return ResourceManager.GetString("Home_Button_AddMultiplePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Username (animation).
        /// </summary>
        internal static string Home_Button_ChangeUsernameAnimation {
            get {
                return ResourceManager.GetString("Home_Button_ChangeUsernameAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Username (no animation).
        /// </summary>
        internal static string Home_Button_ChangeUsernameNoAnimation {
            get {
                return ResourceManager.GetString("Home_Button_ChangeUsernameNoAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout Page demo.
        /// </summary>
        internal static string Home_Button_FlyoutPageDemo {
            get {
                return ResourceManager.GetString("Home_Button_FlyoutPageDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout with URI syntax:.
        /// </summary>
        internal static string Home_Button_LogoutWithUriSyntax {
            get {
                return ResourceManager.GetString("Home_Button_LogoutWithUriSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Tabbed Page on Beta tab.
        /// </summary>
        internal static string Home_Button_StartTabbedPageOnBetaTab {
            get {
                return ResourceManager.GetString("Home_Button_StartTabbedPageOnBetaTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabbed Page demo.
        /// </summary>
        internal static string Home_Button_TabbedPageDemo {
            get {
                return ResourceManager.GetString("Home_Button_TabbedPageDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout navigation:.
        /// </summary>
        internal static string Home_SubHeading_FlyoutNavigation {
            get {
                return ResourceManager.GetString("Home_SubHeading_FlyoutNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modal navigation:.
        /// </summary>
        internal static string Home_SubHeading_ModalNavigation {
            get {
                return ResourceManager.GetString("Home_SubHeading_ModalNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabbed navigation:.
        /// </summary>
        internal static string Home_SubHeading_TabbedNavigation {
            get {
                return ResourceManager.GetString("Home_SubHeading_TabbedNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI navigation:.
        /// </summary>
        internal static string Home_SubHeading_UriNavigation {
            get {
                return ResourceManager.GetString("Home_SubHeading_UriNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}.
        /// </summary>
        internal static string Home_WelcomeMessage {
            get {
                return ResourceManager.GetString("Home_WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burkus.Mvvm.Maui Demo App.
        /// </summary>
        internal static string Login_Heading {
            get {
                return ResourceManager.GetString("Login_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter any data to login to this demo app..
        /// </summary>
        internal static string Login_Instructions {
            get {
                return ResourceManager.GetString("Login_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string Login_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("Login_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account yet? Register here..
        /// </summary>
        internal static string Login_RegisterLink {
            get {
                return ResourceManager.GetString("Login_RegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        internal static string Login_UsernamePlaceholder {
            get {
                return ResourceManager.GetString("Login_UsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password..
        /// </summary>
        internal static string Login_Validation_RequiredPassword {
            get {
                return ResourceManager.GetString("Login_Validation_RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a username..
        /// </summary>
        internal static string Login_Validation_RequiredUsername {
            get {
                return ResourceManager.GetString("Login_Validation_RequiredUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t actually need to register. You can just make up any username and password to login! This is just a demo page for relative navigation..
        /// </summary>
        internal static string Register_Instructions {
            get {
                return ResourceManager.GetString("Register_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminders.
        /// </summary>
        internal static string Reminders_Title {
            get {
                return ResourceManager.GetString("Reminders_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo.
        /// </summary>
        internal static string Todo_Title {
            get {
                return ResourceManager.GetString("Todo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back Three Times.
        /// </summary>
        internal static string UriTest_Button_GoBackThreeTimes {
            get {
                return ResourceManager.GetString("UriTest_Button_GoBackThreeTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back Two Times.
        /// </summary>
        internal static string UriTest_Button_GoBackTwoTimes {
            get {
                return ResourceManager.GetString("UriTest_Button_GoBackTwoTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to change username.
        /// </summary>
        internal static string UriTest_Button_SwitchToChangeUsername {
            get {
                return ResourceManager.GetString("UriTest_Button_SwitchToChangeUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI Testing.
        /// </summary>
        internal static string UriTest_Title {
            get {
                return ResourceManager.GetString("UriTest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudy weather today 🌥️.
        /// </summary>
        internal static string WeatherDescription_Cloudy {
            get {
                return ResourceManager.GetString("WeatherDescription_Cloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning, there is Lightning ⚡.
        /// </summary>
        internal static string WeatherDescription_Lightning {
            get {
                return ResourceManager.GetString("WeatherDescription_Lightning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s Rainy today ☔.
        /// </summary>
        internal static string WeatherDescription_Rainy {
            get {
                return ResourceManager.GetString("WeatherDescription_Rainy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be careful, it&apos;s Stormy ⛈️.
        /// </summary>
        internal static string WeatherDescription_Stormy {
            get {
                return ResourceManager.GetString("WeatherDescription_Stormy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weather is Sunny ☀️.
        /// </summary>
        internal static string WeatherDescription_Sunny {
            get {
                return ResourceManager.GetString("WeatherDescription_Sunny", resourceCulture);
            }
        }
    }
}
