using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Linq;
using System.Text;

namespace Burkus.Mvvm.Maui;

[Generator]
internal class AppSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // register a syntax receiver that will process App class declarations
        var appClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax cds && cds.Identifier.Text == "App",
                transform: static (ctx, _) =>
                {
                    var classDecl = (Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax)ctx.Node;
                    var semanticModel = ctx.SemanticModel;
                    var symbol = semanticModel.GetDeclaredSymbol(classDecl);

                    // check if the App class is partial and inherits from Application
                    var isPartial = classDecl.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword));
                    var baseType = symbol?.BaseType;
                    var appType = semanticModel.Compilation.GetTypeByMetadataName("Microsoft.Maui.Controls.Application");
                    if (symbol != null && isPartial && Microsoft.CodeAnalysis.SymbolEqualityComparer.Default.Equals(baseType, appType))
                    {
                        return symbol;
                    }
                    return null;
                })
            .Where(static s => s != null);

        context.RegisterSourceOutput(appClasses, (spc, appSymbol) =>
        {
            // get the MAUI program we are running in
            var assembly = appSymbol.ContainingAssembly;
            var mauiProgramName = $"{assembly.Name}.MauiProgram";
            var mauiProgram = appSymbol.ContainingAssembly
                .GetTypeByMetadataName(mauiProgramName);

            if (mauiProgram is null)
            {
                throw new Exception("You must have a class called \"MauiProgram\" in your .NET MAUI project.");
            }

            // generate the source code for the CreateWindow method
            var sourceBuilder = $@"// <auto-generated>
//     This code was generated by a tool. Burkus.Mvvm.Maui generated this.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace {mauiProgram.ContainingNamespace.ToDisplayString()};

partial class App
{{
    protected override Window CreateWindow(IActivationState? activationState)
    {{
        Current.MainPage = new NavigationPage();

        var burkusMvvmBuilder = ServiceResolver.Resolve<IBurkusMvvmBuilder>();
        var navigationService = ServiceResolver.Resolve<INavigationService>();
        var serviceProvider = ServiceResolver.GetServiceProvider();

        // perform the user's desired initialization logic
        if (burkusMvvmBuilder.onStartFunc != null)
        {{
            burkusMvvmBuilder.onStartFunc.Invoke(navigationService, serviceProvider);
        }}

        var window = base.CreateWindow(activationState);

#if WINDOWS
        if (window != null)
        {{
            window.Title = AppInfo.Current.Name;
        }}
#endif

        return window;
    }}
}}";

            // add the generated source file to the compilation
            spc.AddSource("App-BurkusMvvmApplication.g", SourceText.From(sourceBuilder, Encoding.UTF8));
        });
    }
}
