using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Text;

namespace Burkus.Mvvm.Maui;

[Generator]
public class PageSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Get the compilation object that represents the user code
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Where(static c => c != null);

        context.RegisterSourceOutput(
            classDeclarations.Combine(context.CompilationProvider),
            (spc, tuple) =>
            {
                var classDeclaration = tuple.Left;
                var compilation = tuple.Right;

                var semanticModel = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
                var classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);

                if (classSymbol == null)
                {
                    return;
                }

                // Get the symbols for the base types
                var contentPageSymbol = compilation.GetTypeByMetadataName("Microsoft.Maui.Controls.ContentPage");
                var flyoutPageSymbol = compilation.GetTypeByMetadataName("Microsoft.Maui.Controls.FlyoutPage");
                var navigationPageSymbol = compilation.GetTypeByMetadataName("Microsoft.Maui.Controls.NavigationPage");
                var tabbedPageSymbol = compilation.GetTypeByMetadataName("Microsoft.Maui.Controls.TabbedPage");
                var skipBackButtonGenerationSymbol = compilation.GetTypeByMetadataName("Burkus.Mvvm.Maui.DisableBackButtonNavigatorAttribute");

                var attributes = classSymbol.GetAttributes();
                var hasAttribute = attributes.Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, skipBackButtonGenerationSymbol));

                if (hasAttribute)
                {
                    // don't generate back button handling for this class
                    return;
                }

                // check if the class symbol inherits from any of the base type symbols
                if (SymbolEqualityComparer.Default.Equals(classSymbol.BaseType, contentPageSymbol) ||
                    SymbolEqualityComparer.Default.Equals(classSymbol.BaseType, flyoutPageSymbol) ||
                    SymbolEqualityComparer.Default.Equals(classSymbol.BaseType, navigationPageSymbol) ||
                    SymbolEqualityComparer.Default.Equals(classSymbol.BaseType, tabbedPageSymbol))
                {
                    // get the name and namespace of the class symbol
                    var typeName = classSymbol.Name;
                    var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();

                    // generate the source code for the HandleBackButtonPressed method
                    var sourceBuilder = $@"// <auto-generated>
//     This code was generated by a tool. Burkus.Mvvm.Maui generated this.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace {namespaceName};

partial class {typeName}
{{
        protected override bool OnBackButtonPressed()
        {{
            return BackButtonNavigator.HandleBackButtonPressed();
        }}
}}";

                    // Add the source file to the generator output
                    spc.AddSource($"{typeName}-HandleBackButton.g.cs", SourceText.From(sourceBuilder, Encoding.UTF8));
                }
            });
    }
}
